language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - coverage run --source=opengraph_io/opengraph_io.py opengraph_io/tests/test_opengraph_io.py
  - coveralls